Repository weniv/MAKE-RE_ver2, pull requests merged in 2023-11, with the labels that each got.

#188 📝 PR: project필수 입력 요소 수정 #187
  src/components/organisms/Component/Career.jsx
  src/components/organisms/Component/Project.jsx
  src/components/templates/Career/Career.jsx
  src/components/templates/Career/CareerPreview.jsx
  src/components/templates/Project/Project.jsx
  src/components/templates/Project/ProjectPreview.jsx
Labels: 🐛 Bug

#191 💄 Style: Header 옵션 추가
  src/components/atoms/Button/ToggleBtn.jsx
  src/components/organisms/Header/Header.jsx
  src/pages/PreviewPage.jsx
  src/pages/WritePage.jsx
Labels: 👆UI, 🔥Must

#194 💄 Style: 탈퇴 완료 페이지 UI 구현
  src/App.jsx
  src/components/atoms/Button/MainBtn.jsx
  src/pages/QuitPage.jsx
  src/pages/index.js
Labels: 👆UI

#196 💄 Style: 마이페이지 이력서 관리 페이지 구현
  package-lock.json
  package.json
  src/App.jsx
  src/assets/icon-alert-circle.svg
  src/assets/icon-more.svg
  src/assets/icon-pencil.svg
  src/components/atoms/ColorIcon/ColorIcon.jsx
  src/components/atoms/Input/DefaultInput.jsx
  src/components/organisms/Component/Resume.jsx
  src/components/organisms/Component/index.js
  src/components/organisms/Header/Header.jsx
  src/components/organisms/Nav/MyPageNav.jsx
  src/index.js
  src/pages/WritePage.jsx
  src/pages/index.js
  src/pages/myResume.jsx
  src/styles/GlobalStyles.jsx
  src/theme/theme.js
Labels: ✨ Feat, 👆UI

#200 📝 PR: 로그인 페이지 UI 작업 #199
  src/App.jsx
  src/assets/github-logo.svg
  src/assets/google-logo.svg
  src/assets/makere-logo.svg
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
  src/pages/index.js
Labels: 👆UI, 🔥Must

#208 💄 Style: 마이페이지 nav 최소 너비 지정
  src/components/organisms/Nav/MyPageNav.jsx
Labels: 👆UI

#210 📝 PR: 회원가입 관련 UI 구현
  src/App.jsx
  src/assets/icon-email-auth.svg
  src/assets/icon-help-circle.svg
  src/components/atoms/Auth/AuthCode.jsx
  src/components/atoms/Auth/Button.jsx
  src/components/atoms/Auth/Input.jsx
  src/components/atoms/Auth/Label.jsx
  src/components/atoms/Auth/Layout.jsx
  src/components/atoms/Auth/Logo.jsx
  src/components/atoms/Auth/WarningMsg.jsx
  src/components/atoms/Auth/index.js
  src/components/organisms/Auth/LabelInput.jsx
  src/components/organisms/Auth/index.js
  src/pages/LoginPage.jsx
  src/pages/SignupDonePage.jsx
  src/pages/SignupPage.jsx
  src/pages/index.js
  src/utils/issuanceCode.js
Labels: ✨ Feat, 👆UI

#212 🔥 Remove: 미리보기 페이지 드래그앤드롭 기능 제거
  src/components/atoms/Nav/NavList.jsx
  src/components/organisms/Nav/NavBar.jsx
Labels: 🐛 Bug

#213 📝 PR: Auth 페이지 링크 연결 및 Header 추가
  src/components/atoms/Auth/Layout.jsx
  src/pages/SignupPage.jsx
Labels: ✨ Feat, 👆UI

#215 📝 PR: 날짜 컴포넌트 레이아웃 수정
  src/components/atoms/PreviewItem/PreviewMonthItem.jsx
  src/components/organisms/ComponentHeader/ComponentHeader.jsx
  src/components/templates/Project/ProjectPreview.jsx
Labels: 👆UI

#216 💄 Style: 프로필, 자기소개 글자 색상 값 지정
  src/components/templates/Intro/IntroPreview.jsx
  src/components/templates/Profile/ProfilePreview.jsx
Labels: 👆UI

#217 ✨ Feat: 이력서 관리 페이지 관련 로직 뼈대 작업
  src/components/organisms/Component/DeleteModal.jsx
  src/components/organisms/Component/Resume.jsx
  src/pages/myResume.jsx
Labels: ✨ Feat

#223 📝 PR: 오버레이 기능 추가
  src/assets/icon-polygon.svg
  src/assets/icon-question-mark.svg
  src/components/atoms/Button/ExplainBtn.jsx
  src/components/organisms/Explain/ExpalinBox.jsx
  src/components/organisms/Explain/Explain.jsx
  src/pages/WritePage.jsx
Labels: 👆UI

#227 📝 PR: 경험 섹션 항목 추가
  src/components/organisms/Component/Experience.jsx
  src/components/templates/Experience/Experience.jsx
Labels: ✨ Feat

#230 ✨ Feat: 교육 및 자격증 섹션 필드 추가
  src/components/atoms/Input/DateInput.jsx
  src/components/organisms/Component/Certificate.jsx
  src/components/organisms/Component/Education.jsx
Labels: ✨ Feat, 👆UI

#234 📝 PR: 아코디언 메뉴 컴포넌트 동작 버그 수정
  src/components/organisms/Component/Career.jsx
  src/components/organisms/Component/Certificate.jsx
  src/components/organisms/Component/Education.jsx
  src/components/organisms/Component/Experience.jsx
  src/components/organisms/Component/Project.jsx
  src/components/organisms/Component/Url.jsx
  src/components/organisms/ComponentHeader/ComponentHeader.jsx
  src/components/templates/Career/Career.jsx
  src/components/templates/Certificate/Certificate.jsx
  src/components/templates/Education/Education.jsx
  src/components/templates/Experience/Experience.jsx
  src/components/templates/Project/Project.jsx
  src/components/templates/Url/Url.jsx
Labels: 🐛 Bug

#235 📝 PR: 프로젝트 설명 파트 PDF 출력시 다크 모드 적용안되는 문제 해결 #231
  src/components/templates/Project/ProjectPreview.jsx
Labels: 🐛 Bug

#237 📝 PR: 커리어 및 프로젝트 입력 페이지 필수 입력 요소 추가
  src/components/atoms/Input/RequireInput.jsx
  src/components/organisms/Component/Career.jsx
  src/components/organisms/Component/Project.jsx
  src/components/organisms/Nav/PreviewBox.jsx
  src/components/templates/Career/CareerPreview.jsx
Labels: 🐛 Bug, 👆UI, 🔥Must
