Repository weniv/MAKE-RE_ver2, pull requests merged in 2023-10, with the labels that each got.

#128 :lipstick: Fix: intro line-height 적용
  src/components/atoms/Input/DefaultTextarea.jsx
Labels: 👆UI

#138 📝 Edit: 작성페이지 섹션별 설명 문구 수정
  src/components/templates/Career/Career.jsx
  src/components/templates/Certificate/Certificate.jsx
  src/components/templates/Education/Education.jsx
  src/components/templates/Experience/Experience.jsx
  src/components/templates/Intro/Intro.jsx
  src/components/templates/Profile/Profile.jsx
  src/components/templates/Project/Project.jsx
  src/components/templates/Url/Url.jsx
Labels: 👆UI

#141 :lipstick: Add: preivew page footer 추가
  src/pages/PreviewPage.jsx
Labels: 👆UI

#147 :lipstick: Fix: 입력 상황에 따른 조건부 렌더링
  src/components/templates/Profile/ProfilePreview.jsx
Labels: 👆UI

#149 ✨ Feat: 메인컬러 적용 파트 구분
  src/App.jsx
  src/components/atoms/Button/MainBtn.jsx
  src/components/atoms/Button/ToggleBtn.jsx
  src/components/atoms/ColorIcon/ColorIcon.jsx
  src/components/atoms/Nav/NavList.jsx
  src/components/organisms/ColorPicker/ColorPicker.jsx
  src/components/organisms/Nav/PreviewBox.jsx
  src/context/PageContext.jsx
Labels: ✨ Feat

#154 🐛 Fix: Career 컴포넌트 Textarea의 height가 가변적으로 설정되도록 수정
  src/components/atoms/Input/DefaultTextarea.jsx
  src/components/organisms/Component/Career.jsx
  src/components/templates/Career/Career.jsx
  src/utils/updateData.jsx
Labels: 🐛 Bug

#157 💄 Style: colorPicker 값 적용 대상 수정
  src/App.jsx
  src/components/atoms/Button/MainBtn.jsx
  src/components/atoms/Button/ToggleBtn.jsx
  src/components/atoms/ColorIcon/ColorIcon.jsx
  src/components/atoms/Nav/NavList.jsx
  src/components/organisms/Header/Header.jsx
  src/components/organisms/Nav/PreviewBox.jsx
  src/components/templates/Profile/Profile.jsx
Labels: 👆UI

#158 💄 Style: 프로젝트 적용 기술 텍스트 색상 고정
  src/components/templates/Project/ProjectPreview.jsx
Labels: 👆UI

#171 💄 Style: nav 체크 아이콘 제거
  src/components/atoms/Nav/NavList.jsx
Labels: 👆UI

#173 💄 Style: ToggleBtn 사이즈 변경
  src/components/atoms/Button/ToggleBtn.jsx
Labels: 👆UI

#175 💄 Style: 타이틀 font-weight 변경
  src/components/atoms/Title/WriteSubtitle.jsx
  src/components/atoms/Title/WriteTitle.jsx
Labels: 👆UI

#177 💄 Style: DefaultTextarea 커스텀 스크롤 추가
  src/components/atoms/Input/DefaultTextarea.jsx
Labels: 👆UI

#181 💄 Style: 컨텐츠 최소 높이 설정을 통한 footer 위치 고정
  src/pages/PreviewPage.jsx
  src/pages/WritePage.jsx
Labels: 👆UI

#182 💄 UI: Skills 미리보기 섹션 구현
  src/components/atoms/SkillList/SkillList.jsx
  src/components/templates/Intro/IntroPreview.jsx
Labels: 👆UI, 🔥Must

#184 💄 Style: textarea 커스텀 스크롤 수정
  src/components/atoms/Input/DefaultTextarea.jsx
  src/styles/GlobalStyles.jsx
Labels: 👆UI
