Repository weniv/MAKE-RE_ver2, pull requests merged in 2023-12, with the labels that each got.

#243 📝 PR: 로그인/회원가입 페이지 다크모드 적용
  src/components/atoms/Auth/AuthCode.jsx
  src/components/atoms/Auth/Input.jsx
  src/components/atoms/Auth/Label.jsx
  src/components/atoms/Auth/Layout.jsx
  src/components/atoms/Auth/WarningMsg.jsx
  src/pages/LoginPage.jsx
  src/pages/SignupPage.jsx
  src/styles/GlobalStyles.jsx
Labels: 🐛 Bug, 👆UI

#244 :bug: Fix: 깃허브 데이터 빈값 예외처리
  src/api/GithubApi.jsx
  src/components/templates/Profile/Profile.jsx
  src/components/templates/Profile/ProfilePreview.jsx
Labels: 🐛 Bug, ✨ Feat

#249 🐛 Edit: 이메일 주소 수정시 "직접 입력" 변경
  src/components/atoms/DropBox/DropBox.jsx
  src/components/templates/Profile/Profile.jsx
Labels: 🐛 Bug

#250 :lipstick: Edit: Intro textarea line-height 변경
  src/components/templates/Intro/Intro.jsx
Labels: 👆UI

#251 :sparkles: Add: 깃허브 커밋이미지 로딩 인디케이터 추가
  src/assets/spinner.gif
  src/components/templates/Profile/ProfilePreview.jsx
  src/utils/useThemeObserver.jsx
Labels: 👆UI

#253 :bug: Edit: 잔디가 없을 때 로딩 인디케이터 보이는 현상 해결
  src/components/templates/Profile/ProfilePreview.jsx
Labels: 🐛 Bug

#256 🐛 Fix: 라우터 경로 수정
  src/App.jsx
  src/components/organisms/Component/Resume.jsx
  src/components/organisms/Header/Header.jsx
  src/components/organisms/Nav/MyPageNav.jsx
  src/components/organisms/Nav/PreviewBox.jsx
  src/pages/LandingPage.jsx
  src/pages/LoginPage.jsx
  src/pages/NotFoundPage.jsx
  src/pages/QuitPage.jsx
  src/pages/SignupDonePage.jsx
  src/pages/SignupPage.jsx
Labels: 🐛 Bug
