Repository weniv/MAKE-RE_ver2, pull requests merged in 2024-01, with the labels that each got.

#268 💄 Style: 미리보기 skills 리스트 스타일 수정
  src/components/atoms/SkillList/SkillList.jsx
  src/components/templates/Intro/IntroPreview.jsx
Labels: 👆UI

#270 🐛 Bug: DefaultTextarea 컴포넌트 height 자동변경 변경 버그 #267
  src/components/atoms/Input/DefaultTextarea.jsx
  src/components/organisms/Component/Career.jsx
  src/components/templates/Career/Career.jsx
Labels: 🐛 Bug, 👆UI

#278 📦 Add: react-snap
  package-lock.json
  package.json
  src/index.js
  src/utils/metaData.jsx
Labels: 🔥Must

#281 ✨ Feat: 랜딩페이지 버튼 이동 링크 변경 (write → 마이페이지)
  src/pages/LandingPage.jsx
Labels: ✨ Feat

#285 ✨ Feat: 이력서 최종 수정일 로직 추가
  src/components/organisms/Component/Resume.jsx
  src/context/ResumeContext.jsx
  src/data/dummy.js
  src/utils/getCurrentDate.jsx
  src/utils/index.js
Labels: ✨ Feat

#284 📝 PR: 마이페이지 이력서 수정 및 삭제 버튼 수정
  src/components/organisms/Component/Resume.jsx
  src/components/templates/Career/Career.jsx
  src/components/templates/Profile/Profile.jsx
Labels: ✨ Feat

#282 📝 PR: 기본 프로필 설정 및 불러오기
  src/components/templates/Profile/DefaultProfile.jsx
  src/components/templates/Profile/Profile.jsx
  src/pages/MyProfilePage.jsx
Labels: ✨ Feat

#294 💄 Style: 기본 프로필 저장 버튼 추가 및 수정
  src/components/templates/Profile/DefaultProfile.jsx
  src/components/templates/Profile/Profile-style.jsx
  src/pages/MyProfilePage.jsx
Labels: 👆UI

#295 🐛Fix: 미리보기 페이지에서 깃헙 잔디 출력되지않던 문제 해결
  src/assets/icon-Left-arrow.svg
  src/components/templates/Profile/Profile.jsx
  src/components/templates/Profile/ProfilePreview.jsx
  src/pages/PreviewPage.jsx
  src/pages/WritePage.jsx
Labels: 🐛 Bug, ✨ Feat

#298 📝 PR: 새로운 이력서 생성시 id 값이 null로 삽입되는 문제 해결 #297
  src/pages/myResumePage.jsx
Labels: 🐛 Bug

#300 ✨ Feat: 기본 프로필 페이지 초기화 시 로컬 스토리지 데이터 가져오기
  package-lock.json
  package.json
  src/components/templates/Profile/DefaultProfile.jsx
Labels: ✨ Feat

#303 🐛 Fix: 기본 프로필 하단 저장 버튼 에러 수정
  src/components/templates/Profile/DefaultProfile.jsx
  src/components/templates/Profile/Profile-style.jsx
  src/context/ProfileContext.jsx
  src/pages/MyProfilePage.jsx
Labels: 🐛 Bug
