Repository weniv/MAKE-RE_ver2, pull requests merged in 2024-02, with the labels that each got.

#310 📝 PR: QA 체크 후 수정사항 반영
  src/components/atoms/Input/DefaultInput.jsx
  src/components/atoms/Input/RequireInput.jsx
  src/components/atoms/PreviewItem/PreviewLink.jsx
  src/components/organisms/Component/Career.jsx
  src/components/organisms/Nav/PreviewBox.jsx
  src/components/templates/Career/CareerPreview.jsx
  src/components/templates/Profile/Profile-style.jsx
  src/components/templates/Profile/Profile.jsx
  src/components/templates/Profile/ProfilePreview.jsx
  src/components/templates/Project/ProjectPreview.jsx
  src/utils/updateData.jsx
Labels: 🐛 Bug

#313 💄 Style: 미리보기 테마 변수 미적용 파트 수정
  src/components/atoms/PreviewItem/PreviewMonthItem.jsx
  src/components/templates/Career/CareerPreview.jsx
  src/components/templates/Project/ProjectPreview.jsx
Labels: 👆UI

#321 ✨ Feat: Header 기능 중복 아이콘 삭제 및 라우팅 변경
  src/components/organisms/Header/Header.jsx
  src/pages/MyProfilePage.jsx
Labels: ✨ Feat

#324 ✨ Feat: 깃허브 아이디 입력하지 않았을 때 빈 잔디 UI 제거
  src/components/templates/Profile/ProfilePreview.jsx
Labels: ✨ Feat

#325 💄UI: 커리어 담당 업무 미리보기 시 줄바꿈 유지
  src/components/templates/Career/CareerPreview.jsx
Labels: 👆UI

#326 🐛 Fix: 랜덤 포커싱 이슈 수정 (첫 번째 input에 자동 포커싱 되도록)
  src/components/atoms/Input/DefaultInput.jsx
  src/components/atoms/Input/RequireInput.jsx
  src/components/organisms/Component/Certificate.jsx
  src/components/organisms/Component/Education.jsx
  src/components/organisms/Component/Experience.jsx
  src/components/organisms/Component/Url.jsx
Labels: 🐛 Bug

#327 📝 PR: GitHub 아이디 변경 방식 변경 #320
  src/components/atoms/Github/GetCommitRecord.jsx
  src/components/templates/Project/Project.jsx
Labels: ✨ Feat

#328 ✨ Feat: ResumeStore 내 최종 수정일 로직 추가
  src/store/ResumeStore.jsx
Labels: ✨ Feat
